mlibrary/spectrum

Gemfile, Gemfile.lock, Rakefile, config/application.rb
* Load Dotenv[-rails] in application start and the Rakefile
* Change Rakefile to get pride/search branches from env variables instead of dot files
* Add argument to `-i` in sed command, 'cause OSX demands it.
=> Set up to use dotenv

Rakefile
=> Add explicit (non-)suffix -i flag in sed for OSX compatibility

Rakefile
Changing rewrite of search's `package.json` (to add in pride's branch) to pure ruby.
=> Found at least three incompatible versions of sed

config/foci/03-onlinejournals.yml
From Ken and Robyn:
- Remove Available Online and Hathi checkboxes
- Remove Format, Date of Publication, Availability, Author, Location, Collection, and Region
Requested Order:
- Subject
- Language
- Place of Publication
- Academic Discipline
=> Update facets for onlinejournals

.dockerignore, .gitignore, Dockerfile, Gemfile, Gemfile.dev, Gemfile.dev.lock, Gemfile.lock, README.md, config/environments/production.rb, docker-compose.yml
* Stop specifying UID/GID in the Dockerfile
* Install code and dependencies as root
* limit application-writable directories.
* .dockerignore and .gitignore files left when
debugging with docker-compose
* Updates to the README.md
* Updates to send logs to stdout
=> Updates for Docker practices

config/fields.yml, config/foci/00-catalog.yml
I think this should solve
https://tools.lib.umich.edu/jira/browse/SEARCH-1381
=> Replaced marc_title with title_display for the catalog

config/fields.yml
Adding some data to config/fields.yml so the new callno_browse, author_browse and subject_browse Header Record Elements are showing up.
=> Adding some data for subject_browse, author_browse and callno_browse

README.md
I think we need to update the ReadMe for the new Search release?
=> Update Readme to new search release v1.15.0

config/fields.yml
Modifying and adding data needed for callnumber browse
=> Adding and massaging Header Record Elements for callno_browse

Gemfile, Gemfile.lock, config/get_this.yml
Not 100% sure this is the correct policy change.
=> Search 1414 get checked out items

Dockerfile, Gemfile, Gemfile.lock, config/get_this.yml, docker-compose.yml
Gemfile.lock is now pulling from latest book_this branch spectrum-json.
=> Changes to get_this.yml

config/get_this.yml
Updates to config.yml so that the problems in the tickets are addressed. See the spectrum-json pull request for more info.
=> SEARCH-853 and SEARCH-1409 Course Reserves and In Process items in Get This

config/fields.yml
That should be all that's needed for SEARCH-1302 ("Improve linking of subject search metadata").
=> Changed type of the lcsh_subjects metatdata component to quoted_search2

local-gems/spectrum-json/lib/spectrum/holding/physical_item_status_text.rb, spec/spectrum/holding/physical_item_status_spec.rb
Building use only and Reading room also show temporary location in status
=> SEARCH-1461 Temporary Locations for Item policy 08 

config/fields.yml, config/foci/02-databases.yml, config/foci/03-onlinejournals.yml, local-gems/spectrum-config/lib/spectrum/config/highly_recommended.rb, local-gems/spectrum-config/lib/spectrum/config/highly_recommended_field.rb
These are going to depend on a schema change for the catalog solr, and a full reindexing before merging.
=> Last fixes for best bets.

local-gems/spectrum-json/lib/spectrum/entities/alma_item.rb, spec/spectrum/entities/alma_item_spec.rb
Takes care of problem in corresponding SEARCH ticket.
=> SEARCH-1563 added logic for properly processing lost items

config/bookplates.yml
Went back to old bookplate links so that the images don't show in SEARCH.
=> SEARCH-1562 reverting bookplate links

local-gems/spectrum-json/lib/spectrum/entities/alma_hold.rb, spec/fixtures/get_this/alma_hold_error_response.json, spec/fixtures/get_this/alma_hold_success_response.json, spec/spectrum/entities/alma_hold_spec.rb
=> Search 1588 only do item level hold

config/get_this.yml, config/locColl.yaml, local-gems/spectrum-json/lib/spectrum/decorators/physical_item_decorator.rb, spec/spectrum/decorators/physical_item_decorator_spec.rb
SPRC Advanced Search options had some typos. Those are fixed here.
Dave in CVGA wants items in SHAP GAME to only have the "Find it in the Library" option.
=> Sprc and cvga updates

local-gems/spectrum-json/lib/spectrum/holding/physical_item_status_text.rb, spec/spectrum/holding/physical_item_status_spec.rb, spec/spectrum/presenters/physical_item_presenter_spec.rb
adds status text for cvga room only items
=> Status text for SHAP GAME items

config/get_this.yml
This addresses [LIBSEARCH-807](https://mlit.atlassian.net/browse/LIBSEARCH-807)
=> fixes ON ORDER get this text

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/advanced_filtering_aggregator.rb, spec/spectrum-config/spectrum/config/advanced_filtering_aggregator_spec.rb
Hopefully fixing the issues with multiple new/previous titles, as well as empty entries for previous title if a new title exists.
=> Libsearch 274

config/instLocs.yaml
[LIBSEARCH-846](https://mlit.atlassian.net/browse/LIBSEARCH-846)
=> fix: typo in HSRS

config/instLocs.yaml, config/locColl.yaml
Takes care of [LIBSEARCH-849](https://mlit.atlassian.net/browse/LIBSEARCH-849)
=> LIBSEARCH-849 HERB to MUSM in advanced Search

Rakefile
Have Rake download profile photos when it would build the Search front-end.
=> Cleaning up the Rake logic for downloading profile photos.

config/alma_workflow_status_labels.json, local-gems/spectrum-json/lib/spectrum/entities/alma_item.rb, local-gems/spectrum-json/lib/spectrum/entities/alma_workflow_status_labels.rb, local-gems/spectrum-json/lib/spectrum/holding/physical_item_status.rb, local-gems/spectrum-json/lib/spectrum/json.rb, local-gems/spectrum-json/lib/spectrum/json/railtie.rb, spec/fixtures/alma_workflow_status_labels.json, spec/spectrum/entities/alma_item_spec.rb, spec/spectrum/entities/alma_workflow_status_labels_spec.rb, spec/spectrum/holding/physical_item_status_spec.rb
Addresses: [LIBSEARCH-843](https://mlit.atlassian.net/browse/LIBSEARCH-843)
=> LIBSEARCH-843 User friendly alma labels

config/get_this.yml
This resolves [LIBSEARCH-821](https://mlit.atlassian.net/browse/LIBSEARCH-821)
=> LIBSEARCH-821 Askwith items can be picked up at the library

config/get_this.yml, local-gems/spectrum-json/lib/spectrum/decorators/physical_item_decorator.rb, local-gems/spectrum-json/lib/spectrum/entities/alma_item.rb, local-gems/spectrum-json/lib/spectrum/holding/no_action.rb, local-gems/spectrum-json/lib/spectrum/holding/physical_item_status.rb, spec/spectrum/decorators/physical_item_decorator_spec.rb, spec/spectrum/entities/alma_item_spec.rb, spec/spectrum/holding/action_spec.rb, spec/spectrum/holding/no_action_spec.rb, spec/spectrum/holding/physical_item_status_spec.rb
Changes for [LIBSEARCH-833](https://mlit.atlassian.net/browse/LIBSEARCH-883)
=> LIBSEARCH-833 game get this

config/get_this.yml, local-gems/spectrum-json/lib/spectrum/bib_record.rb, local-gems/spectrum-json/lib/spectrum/decorators/physical_item_decorator.rb, local-gems/spectrum-json/lib/spectrum/entities/alma_item.rb, spec/fixtures/get_this_policy.yml, spec/spectrum/decorators/physical_item_decorator_spec.rb, spec/spectrum/entities/get_this_options_spec.rb
Addresses [LIBSEARCH-884](https://mlit.atlassian.net/browse/LIBSEARCH-884)
Shouldn't be merged in until after the reindex.
=> Libsearch 884 scan and maps

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/resource_access_field.rb
Provide updated text for databases' access restrictions.
=> Libsearch 189

local-gems/spectrum-config/lib/spectrum/search_engines/primo/doc.rb
Update the link construction for Naxos Video records.
=> Naxos Video links are empty

config/facet_parents.yml
Changing "Health Behavior and Health Education" to "Health Behavior and Health Equity".
https://mlit.atlassian.net/browse/LIBSEARCH-996
=> [LIBSEARCH-996] Update list of academic disciplines in Database and Online Journal browse

.github/workflows/tests.yml, Dockerfile, Gemfile, Gemfile.lock, local-gems/spectrum-json/lib/spectrum/json.rb
Updating the ruby version to 3.3.5.
=> Updates for ruby 3.3

config/locColl.yaml
AAEL BKS and AAEL SER are reportedly being merged into AAEL MAIN.
Once no records are using AAEL BKS and AAEL SER, those lines can be removed.  Though there isn't currently an AAEL SER line.
=> Add AAEL MAIN location.

Gemfile, README.notifications.md, config.ru, config/metrics.yml, config/puma.rb, config/subscriptions.rb, lib/metrics.rb, local-gems/spectrum-config/lib/spectrum/search_engines/primo/engine.rb, local-gems/spectrum-config/lib/spectrum/search_engines/solr.rb, local-gems/spectrum-json/lib/spectrum/json/app.rb, local-gems/spectrum-json/lib/spectrum/json/app/search.rb, local-gems/spectrum-json/lib/spectrum/request/action.rb, local-gems/spectrum-json/lib/spectrum/request/email.rb, local-gems/spectrum-json/lib/spectrum/request/file.rb, local-gems/spectrum-json/lib/spectrum/request/text.rb
Refactoring metrics configuration.
=> Add logging support

config/locColl.yaml
Simon updated all of the locations to be things that actually exist in Alma. 
We also added a few new groups. They are noted in the comments in the yaml file.
=> Update library collections filter

config/fields.yml, config/foci/00-catalog.yml, local-gems/spectrum-config/lib/spectrum/config/conditional_mapped_facet_field.rb
* Update the solr name of the availability field. (new_availability -> availability)
* Provide the availability to the front-end as a field.
=> LIBSEARCH-1044 Updates to availability field
