app/models/spectrum/search_engines/solr.rb, ssctest.rb
The {!field} query crashes hard when presented with a *:* as the query
value. This has become a problem with its use in the `boost`
function query with the new mirlyn relevancy work.
This commit removes a bunch of extraneous solr params (boost, bq,
qf, pf, etc.) iff q=*:*.
=> Remove unneeded solr params on null search (*:*)

config/foci/00-catalog.yml
Adds a comment to `00-catalog.yaml` noting how the field name `title_starts_with` is hacked to be forced to be a phrase in `catalog_controller.rb`. I got worried when my tests of the raw solr field via the solr console gave crappy results
for unquoted searched (e.g., `q=one two qf=title_l`). 
This code predates us (blame says it was written 8 years ago) and I don't know if we're using
that field name on purpose or we just got lucky, but it seems worth a warning.
=> Add comment noting special handling of title_stars_with

config/get_this.yml
This still needs a dependency update to reference the updated spectrum-json that has the method `#not_building_use_only?`. That is in the spectrum-json PR with the same name.
=> SEARCH-1408-building-use-only-fix

Rakefile
We used the presence of npm to determine whether Spectrum should
build Search in production, but we kept that separate in Kubernetes.
Making this an explicit environment variable so that builds with
node/npm can choose whether to build Search with asset precompilation.
=> Make the need to build the Search UI explicit

Dockerfile, README.md, docker-compose.yml, script/docker-startup, script/run-tests
I've created some scripts that simplify launching Spectrum when debugging, and updated the README.md to show how to use those scripts.
Questions specific to this:
* Does adding to `script/` to assist in launching in the application server in Docker deviate from expectations too much?
* Does providing a mechanism to launch WEBrick instead of Puma complicate things too much?
* Does this make other modes of development and debugging harder?
=> Debugging assistance for docker-compose.

config/foci/05-primo-articles.yml
This change lets the query parser know that pmid is a valid field to search in primo.
=> Fix for searching by pmid in Articles.

config/fields.yml, config/foci/05-primo-articles.yml, local-gems/spectrum-config/lib/spectrum/config/field.rb, local-gems/spectrum-config/lib/spectrum/config/primo_source.rb
This change:
1. Creates a `contains` field to hold the metadata
2. Adds `contains` as a search field for the query parser.
3. Extends the field configuration to add metadata for `query_precision` and `query feedback`
4. Updates the PrimoSource class to use the `query_precision` to specify the precision in primo
5. `query_feedback` is not utilized yet, and the specific messages to send have not been identified.
=> Search 1681 article search contains

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/filter.rb, spec/spectrum-config/spectrum/config/filter_spec.rb
* 300a must include alphumeric characters only
* titles and publishers should not have spaces before colons, or trailing colons or trailing slashes.
=> Filters for RIS exports

config/foci/00-catalog.yml
This is a new(ish) field that only holds "authoritative" authors as defined to us by Tech Services.
=> Add field `author_authoritative_search` to author serach

config/get_this.yml, local-gems/spectrum-json/lib/spectrum/decorators/physical_item_decorator.rb, local-gems/spectrum-json/lib/spectrum/entities/get_this_work_order_option.rb, spec/spectrum/decorators/physical_item_decorator_spec.rb, spec/spectrum/entities/get_this_work_order_option_spec.rb
This PR addresses [LIBSEARCH-819](https://mlit.atlassian.net/browse/LIBSEARCH-819)
It marks items in IS-SEEES location in the AcqWorkOrder as `in_international_studies_acquisitions_technical_services`. It has the same wording as items in the labeling as a regular "Pick it up at the library", but the number of days is 5 instead of 3.
The get-this option will look like this:
=> LIBSEARCH-819 IS-SEEES AcqWorkOrder is getable

config/instLocs.yaml, config/locColl.yaml
Chesler was never migrated to Alma. Background is in TDX ticket [3811838](https://teamdynamix.umich.edu/TDNext/Apps/87/Tickets/TicketDet?TicketID=3811838) 
Herbarium needed stacks added. 
SPEC had needed REF, BIND, and RARE
Tickets: [LIBSEARCH-845](https://mlit.atlassian.net/browse/LIBSEARCH-845), [LIBSEARCH-838](https://mlit.atlassian.net/browse/LIBSEARCH-838)
=> LIBSEARCH-845, LIBSEARCH-838 Advanced Search

Rakefile
The webserver was then unable to serve the files when permission was set to 600.
664 is more acceptable in the current deployment arrangement.
=> Profile photos were being downloaded with permission 600.

local-gems/spectrum-json/lib/spectrum/available_online_holding.rb, local-gems/spectrum-json/lib/spectrum/bib_record.rb, local-gems/spectrum-json/lib/spectrum/decorators/physical_item_decorator.rb, local-gems/spectrum-json/lib/spectrum/empty_item_holding.rb, local-gems/spectrum-json/lib/spectrum/entities/alma_item.rb, spec/spectrum/bib_record_spec.rb, spec/spectrum/decorators/physical_item_decorator_spec.rb, spec/spectrum/empty_item_holding_spec.rb, spec/spectrum/entities/alma_item_spec.rb
This pull request corresponds to [LIBSEARCH-879](https://mlit.atlassian.net/browse/LIBSEARCH-879)
It removes `on_site?` and `off_site?`. 
It has `closed_stacks?` and `open_stacks?` be determined by the Alma fulfillment unit and Alma location type. These are updated with a full reindex so we should not deploy this until after a full reindex.
=> Libsearch 879 Closed stacks uses fulfillment unit and location type

local-gems/spectrum-json/lib/spectrum/bib_record.rb, local-gems/spectrum-json/lib/spectrum/presenters/electronic_item_presenter.rb, spec/spectrum/bib_record_spec.rb, spec/spectrum/presenters/electronic_item_presenter_spec.rb
Solr will produce a holding with the library ALMA_DIGITAL for Alma Digital items. These items will have the fields described in the Spectrum::BibRecord::DigitalHolding class. They are presented as if they are Electronic Holdings so are a flavor of the ElectronicItemPresenter.
This is not related to a LIBSEARCH issue. It comes out of a meeting I was in with the Alma Digital team.
=> Alma Digital as a kind of ElectronicItemPresenter

config/fields.yml, spec/spectrum-config/search_engines/primo/engine_spec.rb
> Add the Retraction metadata element to brief and medium view Articles records, as noted in the [metadata spec](https://docs.google.com/spreadsheets/d/1qk13TMdSYHR8RBiXwZJV9I220VZKMdUjsFsjmx3bX48/edit#gid=1491578089).
=> [LIBSEARCH-898] Add Retracted metadata to brief and medium view Articles records

app/models/spectrum/search_engines/solr.rb, config/fields.yml, config/foci/00-catalog.yml, config/search_field.yml, local-gems/spectrum-json/lib/spectrum/field_tree/field.rb, spec/spectrum-config/search_engines/primo/engine_spec.rb
When searching in Catalog by [LC Subject starts with](https://search.lib.umich.edu/catalog?library=All+libraries&query=lc_subject_starts_with%3A(Human+rights)), the search field defaults to `Keyword`. This is because `LC Subject starts with` is not included in the list of fields for the `mirlyn` datastore:
This pull request adds the necessary information to add `LC Subject starts with` to the list of `fields`.
=> Bug: `LC Subject starts with` switches to `Keyword` in search

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/icon_metadata_component.rb
Primo formats appears to have two new formats.  These break with existing format strings in that (a) the facet versions appear to be singular, and (b) there is no word separator.
These format strings are converted for human consumption via a mapping maintained within the field configration.
Additionally, the Reference Entry format does not have an icon associated with it.  The mapping of format, to icons is maintained in the IconMetadataComponent class.
Previously used, and commented out field definitions have also been removed from the fields configuration file.
=> LIBSEARCH-908: Updates for primo formats

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config.rb, local-gems/spectrum-config/lib/spectrum/config/formatted_catalog_published_field.rb, local-gems/spectrum-config/lib/spectrum/config/labeling_aggregator.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_end_with.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_not_end_with.rb, spec/data/formatted_catalog_published_field/args-001.json, spec/data/formatted_catalog_published_field/results-001.json, spec/spectrum-config/spectrum/config/marc_matcher_spec.rb
Fixes for supporting bidirectional text in the catalog's published field.
These changes insert unicode characters at the beginning  and the ending of the field values when the field is in a left-to-right language.
=> Libsearch 774 catalog published

local-gems/spectrum-json/lib/spectrum/entities/alma_item.rb, spec/spectrum/decorators/physical_item_decorator_spec.rb, spec/spectrum/entities/alma_item_spec.rb
Holdings code used to only handle having up to date information on items checked in before indexing. Now it also handles items checked out before indexing.
=> Fix bug where item is checked out before indexing

local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_end_with.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_is.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_not.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_not_end_with.rb, local-gems/spectrum-config/lib/spectrum/config/marc_matcher_where_start_with.rb, spec/spectrum-config/spectrum/config/marc_matcher_where_is_spec.rb, spec/spectrum-config/spectrum/config/marc_matcher_where_not_spec.rb
Bug was with MarchMatcherWhereNot.  It was matching too many things. The logic for all of these clauses were simplified. New tests were introduced to confirm the bug fix is working.
=> LIBSEARCH-894: Bug fix relating to MarcMatcherWhereClause(s).

config/foci/00-catalog.yml, config/foci/02-databases.yml, config/foci/03-journals.yml, config/foci/03-onlinejournals.yml, config/foci/04-website.yml, config/foci/05-primo-articles.yml, local-gems/spectrum-config/lib/spectrum/config/focus.rb, local-gems/spectrum-json/lib/mlibrary_search_parser/transformer/solr/sometimes_quoted_local_params.rb, local-gems/spectrum-json/lib/spectrum/json.rb, local-gems/spectrum-json/lib/spectrum/request/requesty.rb
* Provide an alternative MLibrarySearchParser::Transformer::Solr:: LocalParams class which looks for quoted inputs on title_starts_with fielded searches.
* Allow (require) the transformer to be specified in the DataStore config.
* Update The DataStore (Focus class) to store the transformer.
* Update Spectrum::Request::Requesty to use the transformer named in the DataSto re.
=> Fixes for Database 'title_starts_with' searches.

local-gems/spectrum-json/lib/spectrum/empty_item_holding.rb
Needed to add the method `not_game?` to the `EmptyItemHolding`.
=> LIBSEARCH 939 Get This on an item with "unavailable" barcode never loads request options

local-gems/spectrum-config/lib/spectrum/config/holdings_resource_access_field.rb, local-gems/spectrum-config/lib/spectrum/search_engines/primo/lib_key.rb, local-gems/spectrum-config/lib/spectrum/search_engines/primo/response.rb, local-gems/spectrum-json/lib/spectrum/empty_item_holding.rb
Found some exceptions being raised.
=> 2024 06 07 exceptions

local-gems/spectrum-json/lib/spectrum/bib_record.rb, local-gems/spectrum-json/lib/spectrum/decorators/physical_item_decorator.rb, local-gems/spectrum-json/lib/spectrum/entities/get_this_option.rb, spec/fixtures/get_this/illiad_request.json, spec/fixtures/solr_bib_on_order_with_264.json, spec/spectrum/bib_record_spec.rb, spec/spectrum/decorators/physical_item_decorator_spec.rb, spec/spectrum/entities/get_this_option_spec.rb
Addresses 
* [LIBSEARCH-961](https://mlit.atlassian.net/browse/LIBSEARCH-961)
* [LIBSEARCH-973](https://mlit.atlassian.net/browse/LIBSEARCH-973)
In the ILLiad get-this request form we are changing `date` to `rft.date`. For the date we are using the value from 264 c if 260 c is empty. For `rft.pub` we are using 264 b if 260 b is empty. 
In the ILLiad get-this request form we are changing:
* `aleph_location` to `alma_location`
We are removing `aleph_item_status` because it is not used. 
`alma_location` will have the Location code as well as the display name of the library. Example: GRAD Hatcher Graduate.
=> LIBSEARCH 961 and 973 ILLiad Get This form changes

local-gems/spectrum-config/lib/spectrum/search_engines/primo/doc.rb
Metadata for records without fulltext is 'no_fulltext' which had a false positive with the previous code.
=> Bugfix for article full text availability

config/fields.yml
From [LIBSEARCH-1042](https://mlit.atlassian.net/browse/LIBSEARCH-1042):
> Catalog, medium view:
> * Add Summary (after 230 characters, truncate and replace positions 231+ with an ellipsis)
> * Add Subjects (LCSH), limited to first 3 results with a “Show all ##” button to display all
>
> Articles, medium view:
> * Add Abstract (after 230 characters, truncate and replace positions 231+ with an ellipsis)
> * Add Subjects, limited to first 3 results with a “Show all ##” button to display all 
This pull request displays the necessary data for the views.
`quoted_search3` was chosen for `lc_subject_display` so the `| Browse in subject list` link would not appear, as it does not appear for displayed authors in `medium` view.
The [pull request](https://github.com/mlibrary/search/pull/507) for …
=> [LIBSEARCH-1042] Update Articles & Catalog medium view

config/fields.yml
Primo doesn't seem to give a separate "start page" and "end page". There is a pages field, though, and we're using that in the UI.
This puts the pages into the SP field for RIS exports.
=> LIBSEARCH-1036 Putting article page ranges into the RIS SP field

Gemfile, Gemfile.lock, config.ru
Leveraging an optional environement variable, RACK_BLOCKLIST_IP to declare blocked IP addresses.  It splits on \s, so fill the variable with space-separated IP addresses.
This is intended for short-term blocking in response to the Christmas Eve Primo/Alma API Limit threshold and misbehaving Search clients.
Long-term blocking should be handled by the load balancer.
=> Adding Rack::Attack

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/csl_type.rb
Bibtex uses the type value, and articles weren't passing those along.
=> LIBSEARCH-160 Fixing bibtex citations

config/fields.yml
The positioning of the `abstract` field [has changed](https://github.com/mlibrary/search/pull/524) for medium Article records. The field no longer needs to be displayed in the metadata.
This pull request fixes [LIBSEARCH-1052](https://mlit.atlassian.net/browse/LIBSEARCH-1052).
=> [LIBSEARCH-1052] Change position of Abstract in Articles medium view results

config/locColl.yaml
The Alma data for Shapiro locations has been updated. The location list has been updated to reflect that.
These Shapiro location codes have been added:
* On Display - Hatcher/Shapiro (DISP)
* Shapiro - Overflow Collection (FLOW)
* Shapiro Basement Government Publications (GOV)
* Unbound serials (SERU)
* Unassigned location (UNASSIGNED)
These Shapiro locations have been removed:
* Basement Compact Shelving (SBCS)
* Undergrad Periodical Shelves - 2nd Floor (PER)
This pull request closes [LIBSEARCH-1055](https://mlit.atlassian.net/browse/LIBSEARCH-1055).
=> [LIBSEARCH-1055] Update Shapiro locations in Catalog Advanced Search

config/fields.yml, config/foci/05-primo-articles.yml, local-gems/spectrum-config/lib/spectrum/config/filter.rb
The peer_reviwed field is either Y when the Primo API results indicate a record is peer reviwed.  Or N otherwise.
=> LIBSEARCH-439 Primo peer reviwed field

config/fields.yml
Following an email conversation with Ken and Monique, this would display transliterated other_titles that were otherwise being ignored.
=> LIBSEARCH-1082 Add transliterated other_titles for marc 730, 740

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/filtered_labeling_aggregator.rb
On RTL author and contributor fields, punctuation is out of place. This change:
* Refactors the filtered_labeling_aggregator to carry a possible prefix and suffix
* Adds the directionality prefix and suffix to the start and end of the fields for main_author and contributor..
=> LIBSEARCH-971 Punctuation out of place

local-gems/spectrum-json/lib/spectrum/request/requesty.rb
Primo and Summon use a page number and page size for pagination. Spectrum and Solr use an offset and count.
Thus we need to compute the page number and page size for the search. Spectrum supports arbitrary values for page number and page size, thus in order to fetch the results in a single request we fetch a range of records and return a slice of the results.
For example, start=45 and count=10 could be met with page_size=15, page=4, slice=[0, 10]
Also start begins at 0, and page begins at 1.
=> Refactor the page/page_size computation

config/fields.yml, local-gems/spectrum-config/lib/spectrum/config/field.rb
This fetches author lists from a field where they are an array. It also ensures that search queries continue to work, and fixes default values related to query generation in primo.
=> LIBSEARCH-148 Author lists in Articles

config/metrics.yml, config/subscriptions.rb
* Dropping labels for query_requested_records and response_records_matched
* Reduced values in the histogram
* Reduced some of the values in the source
=> Reducing cardinality in api response metrics

Gemfile, Gemfile.lock, local-gems/spectrum-json/lib/spectrum/alma_client.rb
In production we were getting errors like: `Errno::EMFILE - too many open files`. This is mentioned as a potential problem in the [HTTPX Faraday adapter docs](https://honeyryderchuck.gitlab.io/httpx/wiki/Faraday-Adapter)
The AlmaRestClient gem has been updated to allow sending an array of parameters for the `http_adapter`. This PR uses the updated gem version, and sets `persistent: false` for the httpx adapter.
=> update alma_rest_client; turn off persistence

local-gems/spectrum-config/lib/spectrum/search_engines/primo/doc.rb
We might be able to leverage Primo's native UI's link resolver in M Get It.
To do so we need to fetch data from the primo API.  So we will have to pass the record id along.
=> Add rft_id=info:primo/$id to the OpenURL

local-gems/spectrum-config/lib/spectrum/config/focus.rb
This endpoint isn't used anymore.
=> Remove ids endpoint.
